[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

[dev]
  functions = "functions"
  command = "npm run dev" 
  targetPort = 8080 
  framework = "#custom"
  publish = "build" 
