# example netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"


  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
[dev]
  functions = "functions"
  framework = "#static"
  publish = "public" 

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
