[build]
  command = "cross-env NODE_ENV=production cd functions && npm i && cd.. && npm run build"
  functions = "functions"
  publish = "build"

[dev]
  functions = "functions"
  command = "npm run dev" 
  targetPort = 8080 
  framework = "#custom"
  publish = "build" 
